// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvRzAdf46XU_spaBuw6pszDE45Ni6rI54',
    appId: '1:936722234144:web:9e5e66314cd4a56359b545',
    messagingSenderId: '936722234144',
    projectId: 'voiceinvoice-e8ae4',
    authDomain: 'voiceinvoice-e8ae4.firebaseapp.com',
    storageBucket: 'voiceinvoice-e8ae4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-lGbQRCRLLarzInhivlNr4pXAFq0ZpQ',
    appId: '1:936722234144:android:514006b74b109b8659b545',
    messagingSenderId: '936722234144',
    projectId: 'voiceinvoice-e8ae4',
    storageBucket: 'voiceinvoice-e8ae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5R7tfADhX-urOypBIJpB1aIV_sFzepeA',
    appId: '1:936722234144:ios:18f1e20e423affb059b545',
    messagingSenderId: '936722234144',
    projectId: 'voiceinvoice-e8ae4',
    storageBucket: 'voiceinvoice-e8ae4.firebasestorage.app',
    iosBundleId: 'com.synodic.voiceinvoice',
  );
}
